version: '{build}'
image: Visual Studio 2017
install:
- set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\;%PATH%
- ps: Install-Product node 6
- npm install --global npm
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: md -Name nupkg | .\build\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: g0PMdJ19aUEvtTZ9VcNQ5rW0ERvxArloSOPd/7SSPvtwd+Ei4BMMEcb5wg4TcHTM
  on:
    branch: master
    appveyor_repo_tag: true